SurfsUpIdentity/SurfsUpIdentity/Models/SurfSpot.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace SurfsUpIdentity.Models
{
    public class SurfSpot
    {
        public int Id { get; set; }
        public string SpotName { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string ImagePath { get; set; }
        public int PostCode { get; set; }
        public string City { get; set; }
        
        [NotMapped]
        public List<string> NewFileName { get; set; } = new List<string>();
    }
}

SurfsUpIdentity/SurfsUpIdentity/ViewModels/SurfSpotViewModel.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using SurfsUpIdentity.Models;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using SurfsUpIdentity.Enums;

namespace SurfsUpIdentity.ViewModels
{
    public class SurfSpotViewModel
    {
        [Required(ErrorMessage = "Titel er påkrævet")]
        [DisplayName("Titel")]
        [StringLength(100, MinimumLength = 5)]
        public string Title { get; set; }

        [Required(ErrorMessage = "Indtast en postnummer")]
        [DisplayName("Postnummer")]
        public int PostCode { get; set; }

        [Required(ErrorMessage = "Indtast latitude")]
        [DisplayName("Latitude")]
        public string Latitude { get; set; }

        [Required(ErrorMessage = "Indtast longitude")]
        [DisplayName("Longitude")]
        public string Longitude { get; set; }

        [Required(ErrorMessage = "Indtast by")]
        [DisplayName("By")]
        public string City { get; set; }

        [Required(ErrorMessage = "Der skal vælges et billede")]
        [FileExtensions(Extensions = "jpeg,jpg,png", ErrorMessage = "Billedet skal være i jpg eller png format")]
        [DisplayName("Billede")]
        public IFormFile Image { get; set; }

        public string ImagePath { get; set; }
        public WeatherData weatherData {get;set;}

        public List<SpotReview> Reviews { get; set; }

        public SpotReview SpotReview { get; set; }

        public int SpotID { get; set; }
        


        public bool IsNice = false;
        
        public static implicit operator SurfSpotViewModel(SurfSpot surfSpot)
        {
            return new SurfSpotViewModel()
            {
                Title = surfSpot.SpotName,
                PostCode = surfSpot.PostCode,
                Longitude = surfSpot.Longitude,
                Latitude = surfSpot.Latitude,
                City = surfSpot.City,
                ImagePath = surfSpot.ImagePath,
                SpotID = surfSpot.Id
            };
        }

        public static implicit operator SurfSpot(SurfSpotViewModel surfSpotViewModel)
        {
            return new SurfSpot()
            {
                SpotName = surfSpotViewModel.Title,
                PostCode = surfSpotViewModel.PostCode,
                Longitude = surfSpotViewModel.Longitude,
                Latitude = surfSpotViewModel.Latitude,
                City = surfSpotViewModel.City,
                ImagePath = surfSpotViewModel.ImagePath,
                Id = surfSpotViewModel.SpotID
            };
        }
    }
}

SurfsUpIdentity/SurfsUpIdentity/Controllers/SurfspotController.cs
using Microsoft.AspNetCore.Mvc;
using SurfsUpIdentity.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SurfsUpIdentity.ViewModels;
using System.Net.Http;
using System.Text;
using System.Net.Mime;
using System.Net.Http.Headers;
using System.Text.Json.Serialization;
using System.Text.Json;
using SurfsUpIdentity.Models;
using Microsoft.AspNetCore.Identity;
using SurfsUpIdentity.Utility;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Razor.Compilation;

namespace SurfsUpIdentity.Controllers
{
    [Route("[controller]")]
    public class SurfspotController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHttpClientFactory _clientFactory;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private SurfSpotViewModel _viewModel;
        private UserManager<User> _userManager;

        public SurfspotController(ApplicationDbContext context, IHttpClientFactory clientFactory, UserManager<User> userManager, IWebHostEnvironment hostingEnvironment)
        {
            _context = context;
            _clientFactory = clientFactory;
            _viewModel = new SurfSpotViewModel();
            _userManager = userManager;
            this._hostingEnvironment = hostingEnvironment;

        }

        [HttpGet]
        [Route("Index")]
        public IActionResult Index()
        {

            List<SurfSpot> surfSpots =_context.SurfSpots.ToList();

            List<SurfSpotViewModel> SurfSpotViewmodels = new List<SurfSpotViewModel>();

            foreach (var spot in surfSpots)
            {
                SurfSpotViewmodels.Add(spot);
            }

            return View(SurfSpotViewmodels);
        }

        [Authorize]
        [Route("AddSurfSpot")]
        public IActionResult AddSurfSpot()
        {
            return View();
        }

        [HttpPost]
        [Route("AddSurfSpot")]
        public async Task<IActionResult> AddSurfSpot(SurfSpotViewModel model)
        {

            if (model.Image != null) //model.Title != null && model.Description != null &&
            {
                await FileHandler.SaveFile(_hostingEnvironment, model);

                _context.SurfSpots.Add(model);
                _context.SaveChanges();
                return Redirect("/Surfspot/Index");
            }
            return View(model);
        }

        [Route("SurfSpot")]
        public async Task<IActionResult> SurfSpot(SurfSpotViewModel surfSpot)
        {
            // Hent vejrdata

            DateTime start = DateTime.Now;
            long UnixStart = ((DateTimeOffset)start).ToUnixTimeSeconds();

            int multiplier = 0;

            var user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                if (user.IsPremium)
                {
                    multiplier = 10;
                }
                
            }
            
            long UnixEnd = UnixStart + 3600 * multiplier;

            var client = _clientFactory.CreateClient();

            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("8b180ae6-2daa-11ec-8169-0242ac130002-8b180b7c-2daa-11ec-8169-0242ac130002");
            var response = await client.GetAsync($"https://api.stormglass.io/v2/weather/point?lat={surfSpot.Latitude}&lng={surfSpot.Longitude}&start={UnixStart}&end={UnixEnd}&params=airTemperature,waveHeight,wavePeriod,waterTemperature,gust,windSpeed&source=noaa");

            surfSpot.weatherData = JsonSerializer.Deserialize<WeatherData>(await response.Content.ReadAsStringAsync());
            
            //TEST SENDER ALLE REVIEWS TIL DET VALGTE SURFSPOT
            
            surfSpot.Reviews = _context.SpotReviews.Where(x=>x.SpotId == surfSpot.SpotID).ToList();

            WeatherDeterminator determinator = new WeatherDeterminator();
            determinator.IsWeatherNice(surfSpot);

            //Sende vejrdata og surfspot til viewet
            

            return View(surfSpot);
        }
        [HttpPost]
        public async Task<IActionResult> SubmitReview(SurfSpotViewModel model)
        {
            //var spotReview = new SpotReview();
            model.SpotReview.Date = DateTime.Now;
            //spotReview.Description = model.SpotReview.Description;
            //spotReview.Title = model.SpotReview.Title;
            model.SpotReview.User = await _userManager.GetUserAsync(User);
            model.SpotReview.SpotId = model.SpotID;
            //spotReview.NumberOfPeople = model.NumberOfPeople;
            //spotReview.WaveQuality = model.WaveQuality;
            model.SpotReview.Image = (await FileHandler.SaveFile(_hostingEnvironment, model)).ImagePath;
            _context.SpotReviews.Add(model.SpotReview);
            _context.SaveChanges();
            model = _context.SurfSpots.Find(model.SpotID);
            return RedirectToAction("SurfSpot",model);
        }
    }
}

SurfsUpIdentity/SurfsUpIdentity/Views/Surfspot/AddSurfSpot.cshtml
@model SurfsUpIdentity.ViewModels.SurfSpotViewModel;



<section class="single-page-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Nyt Surfspot</h1>
                
            </div>
        </div>
    </div>
</section>

<section class="align-content-center" style="margin-top: 50px">
    <div class="container" style="width: 60vw">
        <h2 class="align-content-center">Del et nyt surfspot</h2>
        <p>
            <br /><br />
            <strong>Udfyld formularen herunder for at dele det nye surfspot med andre surfere.</strong>

        </p>
    </div>

</section>

<!--Start Contact Us
   =========================================== -->
<section class="contact-us" id="contact">

    <div class="contact-form">
        <div class="container">

           @using (Html.BeginForm("AddSurfSpot", "Surfspot", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                Html.ValidationSummary();
            <div class="row">

                <div class="col">
                    <div class="form-group ">
                        @Html.LabelFor(x => x.Title)
                        @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Title)
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.Latitude)
                        @Html.TextBoxFor(x => x.Latitude, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Latitude)
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(x => x.Longitude)
                        @Html.TextBoxFor(x => x.Longitude, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Longitude)
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        @Html.LabelFor(x => x.City)
                        @Html.TextBoxFor(x => x.City, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.City)
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(x => x.PostCode)
                        @Html.TextBoxFor(x => x.PostCode, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.PostCode)
                    </div>

                    <div class="form-group ">
                        @Html.LabelFor(x => x.Image)
                        @Html.TextBoxFor(x => x.Image, new { Type = "file", @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Image)
                    </div>
                </div>
            </div>
                   
                <div id="cf-submit" class="text-center" style="margin-top: 30px">
                    <Input type="submit" class="btn btn-primary btn-lg" value="Del Nyt Surfspot" />
                </div>
            }
           
        </div>

    </div>

</section> <!-- end section -->

SurfsUpIdentity/SurfsUpIdentity/Views/Surfspot/Index.cshtml
@model List<SurfSpotViewModel>

<section class="single-page-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>Surfspots</h2>
            </div>
        </div>
    </div>
</section>


<section>

    <div class="container">
        <h2 class="text-center">Spots</h2>
        <p class="text-center">Se alle vores spots i listen herunder</p>
        <a href="@Url.Action("AddSurfSpot", "Surfspot")">Tilføj nyt surfspot</a>
        <div class="card-group">

            <!--bootstrap card with 3 horizontal images-->
            <div class="row align-content-md-around mt-3">
                @foreach (var item in Model)
                {
                    <div class="card col-md-4">
                        <h1 class="text-center">@item.Title</h1>
                        <a href="@Url.Action("SurfSpot", "SurfSpot", @item)">
                            <img class="img-thumbnail" src="~/Upload/@item.ImagePath">
                        </a>

                        <div class="card-body">
                            <h3 class="card-title">@item.City, @item.PostCode</h3>
                        </div>
                    </div>
                }
                </div>
            </div>
        </div>
</section>

SurfsUpIdentity/SurfsUpIdentity/Views/Surfspot/SurfSpot.cshtml
@using SurfsUpIdentity.Enums
@model SurfsUpIdentity.ViewModels.SurfSpotViewModel;

<section class="single-page-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>@Model.Title</h2>
            </div>
        </div>
    </div>
</section>

<div class="text-center m-4">
    <img class="w-25" src="~/Upload/@Model.ImagePath" alt="Alternate Text" />

</div>
<div>


</div>
    <div class="text-center">
        @if (Model.IsNice)
        {
            <H2>Forholdendene virker gode for at surfe</H2>
        }
        else
        {
            <h2>Forholdendene virker dårlige for surfing</h2>
        }
    </div>

<div class="row justify-content-center mb-4" style="width: 100vw">
    <div class="col-auto">

        <table class="table table-responsive text-center">
            <tr>
                <th scope="col">Tid</th>
                <th scope="col">Temperatur °C</th>
                <th scope="col">Bølgehøjde m</th>
                <th scope="col">Vandtemperatur °C</th>
                <th scope="col">Vindstyrke</th>
                <th scope="col">Bølgeperiode sek</th>
                <th scope="col">Vindhastighed m/s</th>
            </tr>
            @foreach (var hour in Model.weatherData.Hours)
            {
                <tr>
                    <td scope="row">@hour.Time.ToString("HH:mm")</td>
                    <td>@Math.Round(hour.AirTemperature.Noaa)</td>
                    <td>@hour.WaveHeight.Noaa</td>
                    <td>@Math.Round(hour.WaterTemperature.Noaa)</td>
                    <td>@Math.Round(hour.Gust.Noaa)</td>
                    <td>@Math.Round(hour.WavePeriod.Noaa)</td>
                    <td>@Math.Round(hour.WindSpeed.Noaa)</td>
                </tr>
            }

        </table>
    </div>
</div>
<div class="container mt-30">

    <div class="col-10 mt-50" style="width:50vw">
        <h2 class="text-center mt-8">Beskriv din oplevelse</h2>
        @using (Html.BeginForm("SubmitReview", "SurfSpot", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="row">

                <div class="col">
                    <div class="form-group">
                        @Html.LabelFor(x => x.SpotReview.Title)
                        @Html.TextBoxFor(x => x.SpotReview.Title, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.SpotReview.Description)
                        @Html.TextAreaFor(x => x.SpotReview.Description, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.SpotReview.NumberOfPeople)
                        @Html.TextAreaFor(x => x.SpotReview.NumberOfPeople, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.SpotReview.WaveQuality)
                        @Html.DropDownListFor(x => x.SpotReview.WaveQuality, new SelectList(Enum.GetValues(typeof(WaveQuality))), "Vælg bølgekvailitet", new { @class = "form-control" })
                    </div>
                    <div class="form-group ">
                        @Html.LabelFor(x => x.Image)
                        @Html.TextBoxFor(x => x.Image, new { Type = "file", @multiple = "multiple", @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Image)
                    </div>
                    <div>
                        <div hidden="hidden"> @Html.HiddenFor(x => x.SpotID)</div>
                        <button type="submit" class="p-2 btn-primary mb-2">Send Kommentar</button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<div class="container mt-50">
        
    <div>
        @if (Model.Reviews != null)
        {
            <h2 class="col-10">Hvad siger andre om spottet?</h2>

            @foreach (var review in Model.Reviews)
            {
                <div class="mb-5 card">
                    <div class="card-header text-center">
                        <h3 style="font-size: medium">@review.Title</h3>
                    </div>
                    <div class="card-body">
                        <h6>Beskrivelse:</h6> @review.Description<br />
                        <h6>Antal mennesker på stranden:</h6>@review.NumberOfPeople<br />
                        <h6>Bølgekvalitet:</h6>@review.WaveQuality <br />
                        <img src="~/Upload/@review.Image" alt="Alternate Text" />
                    </div>
                    <div class="card-footer">
                        <p class="float-right" style="color:darkgray">@review.Date.ToShortDateString()</p>
                    </div>
                </div>
            }
        }
    </div>
</div>