SurfsUpIdentity/SurfsUpIdentity/Controllers/BorrowEquipmentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SurfsUpIdentity.Data;
using SurfsUpIdentity.Models;
using SurfsUpIdentity.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text.Json;
using System.Threading.Tasks;

namespace SurfsUpIdentity.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [Route("[controller]")]
    public class BorrowEquipmentController : Controller
    {
        private readonly ILogger<BorrowEquipmentController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly IHttpClientFactory _clientFactory;

        public BorrowEquipmentController(ILogger<BorrowEquipmentController> logger, ApplicationDbContext context, IHttpClientFactory clientFactory)
        {
            _logger = logger;
            _context = context;
            _clientFactory = clientFactory;
        }
        [HttpGet]
        [Route("Index")]
        [Route("Index/{searchString}")]
        public async Task<IActionResult> Index(string searchString)
        {
            var client = _clientFactory.CreateClient("equipments");

            IEnumerable<Equipment> equipmentList = await client.GetFromJsonAsync<IEnumerable<Equipment>>("https://localhost:44318/Equipment/get");

            //List<Equipment> equipmentList = await _context.Equipments.ToListAsync();
            // Eager loading: (lazy loading initialized in startup.cs)
            //List<Equipment> equipmentList = await _context.Equipments.Include(x => x.User).ThenInclude(x => x.City).ToListAsync();

            ViewData["searchBoardType"] = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                equipmentList = equipmentList.Where(e => e.BoardType.ToString().ToLower().Contains(searchString.ToLower()));
            }

            return View(equipmentList.ToList());
        }

        [Route("Payment")]
        public async Task<IActionResult> Payment(Equipment equipment)
        {
            equipment.User =  (await _context.Equipments.FindAsync(equipment.EquipmentId)).User;
            equipment.User.City = (await  _context.Users.FindAsync(equipment.User.Id)).City;
            return View(equipment);
        }

        [Route("LenderInfo")]
        public IActionResult LenderInfo(User user)
        {
            return View(user);
        }

        [Route("Partners")]
        public IActionResult Partners()
        {
            //Call Partner APIs
            //Retrieve their equipment
            List<PartnerEquipment> list = new List<PartnerEquipment>();
            //Convert it to PartnerEquipment

            return View(list);
        }
    }
}

SurfsUpIdentity/SurfsUpIdentity/Controllers/LendEquipmentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting.Server.Features;
using SurfsUpIdentity.Data;
using SurfsUpIdentity.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using SurfsUpIdentity.Areas.Identity.Pages.Account;
using SurfsUpIdentity.Models;
using SurfsUpIdentity.Utility;

namespace SurfsUpIdentity.Controllers
{
    [Route("[controller]")]
    public class LendEquipmentController : Controller
    {
        public ApplicationDbContext DbContext { get; set; }
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly UserManager<User> _userManager;

        public bool IsAuthenticated { get; set; }

        public LendEquipmentController(ApplicationDbContext applicationDbContext, IWebHostEnvironment hostingEnvironment, UserManager<User> userManager)
        {
            DbContext = applicationDbContext;
            this._hostingEnvironment = hostingEnvironment;
            _userManager = userManager;

        }

        [Authorize]
        [Route("Index")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Route("Index")]
        public async Task<IActionResult> Index(LendOutEquipmentViewModel model)
        {

            if (model.Picture!=null) //model.Title != null && model.Description != null &&
            {
                long size = model.Picture.Sum(f => f.Length);

                model.UserId = _userManager.GetUserId(User);

                await FileHandler.SaveFile(_hostingEnvironment, model);

                DbContext.Equipments.Add(model);
                DbContext.SaveChanges();
                return Redirect("/BorrowEquipment/Index");
            }

            return View(model);
        }
        

    }
}
    

SurfsUpIdentity/SurfsUpIdentity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-BoardType" content="text/html; charset=UTF-8">
    <meta name="description" content="Bingo One page parallax responsive HTML Template ">

    <meta name="author" content="Themefisher.com">

    <title>SurfsUp</title>

    <!-- Mobile Specific Meta
      ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="~/images/favicon.png" />

    <!-- CSS
    ================================================== -->
    <!-- Themefisher Icon font -->
    <link rel="stylesheet" href="~/plugins/themefisher-font/style.css">
    <!-- bootstrap.min css -->
    <link rel="stylesheet" href="~/plugins/bootstrap/css/bootstrap.min.css">
    <!-- Lightbox.min css -->
    <link rel="stylesheet" href="~/plugins/lightbox2/dist/css/lightbox.min.css">
    <!-- animation css -->
    <link rel="stylesheet" href="~/plugins/animate/animate.css">
    <!-- Slick Carousel -->
    <link rel="stylesheet" href="~/plugins/slick/slick.css">
    <!-- Main Stylesheet -->
    <link rel="stylesheet" href="~/css/style.css">

</head>

<body id="body">

    <!--
     Start Preloader
     ==================================== -->
    <div id="preloader">
        <div class='preloader'>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
    <!--
    End Preloader
    ==================================== -->
    <!--
    Fixed Navigation
    ==================================== -->
    <header class="navigation fixed-top">
        <div class="container">
            <!-- main nav -->
            <nav class="navbar navbar-expand-lg navbar-light">
                <!-- logo -->
                <a class="navbar-brand logo" href="@Url.Action("Index","Home")">
                    <img class="logo-default" src="~/images/logos/logo-bold.png" alt="Logo" width="130" height="42"/>
                    <img class="logo-white" src="~/images/logos/logo-white-bold.png" alt="Logo" width="130" height="42"/>
                   
                </a>
                <!-- /logo -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                        aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navigation">
                    <ul class="navbar-nav ml-auto text-center">
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index","Home")">Forside</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="@Url.Action("About","Home")">Om Os</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="@Url.Action("Index","BorrowEquipment")">Lej Udstyr</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="@Url.Action("Index","LendEquipment")">Udlej Udstyr</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="@Url.Action("Index","SurfSpot")">Surfspots</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="@Url.Action("Contact","Home")">Kontakt Os</a>
                        </li>
                        <li class="nav-item">
                            <partial name="_LoginPartial"/>
                        </li>
                    </ul>
                </div>
            </nav>
            <!-- /main nav -->
        </div>
    </header>
    <!--
    End Fixed Navigation
    ==================================== -->



    @RenderBody()


    <footer id="footer" class="bg-one">
        <div class="top-footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-3 col-md-3 col-lg-3">
                        <h3>Om Os</h3>
                        <p>SurfsUp forsøger at skabe en bedre planet ved at tilbyde udlejning af surfudstyr og oprydning af strande</p>
                    </div>
                    <!-- End of .col-sm-3 -->

                    <div class="col-sm-3 col-md-3 col-lg-3">
                        <ul>
                            <li><h3>Vores Udlejning</h3></li>
                            <li><a href="@Url.ActionLink("index","BorrowEquipment")">Lej Kano udstyr</a></li>
                            <li><a href="@Url.ActionLink("index","BorrowEquipment")">Lej Kitesurfing udstyr</a></li>
                            <li><a href="@Url.ActionLink("index","BorrowEquipment")">Lej Vindsurfing udstyr</a></li>
                        </ul>
                    </div>
                    <!-- End of .col-sm-3 -->

                    <div class="col-sm-3 col-md-3 col-lg-3">
                        <ul>
                            <li><h3>Hurtige Links</h3></li>
                            <li><a href="@Url.ActionLink("index","LendEquipment")">Udlej Udstyr</a></li>
                            <li><a href="@Url.ActionLink("index","BorrowEquipment")">Lej Udstyr</a></li>
                            <li><a href="@Url.ActionLink("About","Home")">Om Os</a></li>
                            <li><a href="@Url.ActionLink("Contact","home")">Kontakt Os</a></li>
                        </ul>
                    </div>
                    <!-- End of .col-sm-3 -->

                    <div class="col-sm-3 col-md-3 col-lg-3">
                        <ul>
                            <li><h3>Forbind med os på Sociale Medier</h3></li>
                            <li><a href="#">Facebook</a></li>
                            <li><a href="#">Twitter</a></li>
                        </ul>
                    </div>
                    <!-- End of .col-sm-3 -->

                </div>
            </div> <!-- end container -->
        </div>
        <div class="footer-bottom">
            <h5>Copyright @DateTime.Now.Year All rights reserved.</h5>
            <h6>Design and Developed by <a href="">SurfsUp</a></h6>
        </div>
    </footer> <!-- end footer -->
    <!-- end Footer Area
    ========================================== -->
    <!--
    Essential Scripts
    =====================================-->
    <!-- Main jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- Google Map -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"></script>
    <script src="~/plugins/google-map/gmap.js"></script>

    <!-- Form Validation -->
    <script src="~/plugins/form-validation/jquery.form.js"></script>
    <script src="~/plugins/form-validation/jquery.validate.min.js"></script>

    <!-- Bootstrap4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.min.js"></script>
    <!-- Parallax -->
    <script src="~/plugins/parallax/jquery.parallax-1.1.3.js"></script>
    <!-- lightbox -->
    <script src="~/plugins/lightbox2/dist/js/lightbox.min.js"></script>
    <!-- Owl Carousel -->
    <script src="~/plugins/slick/slick.min.js"></script>
    <!-- filter -->
    <script src="~/plugins/filterizr/jquery.filterizr.min.js"></script>
    <!-- Smooth Scroll js -->
    <script src="~/plugins/smooth-scroll/smooth-scroll.min.js"></script>

    <!-- Custom js -->
    <script src="~/js/script.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SurfsUpIdentity/SurfsUpIdentity/Views/Shared/_Review.cshtml
@model SpotReview

<div class="container" style="width:50vw">
    <h2 class="text-center mt-5">Beskriv din oplevelse</h2>
    @using (Html.BeginForm("SubmitReview", "SurfSpot", FormMethod.Post, new {enctype = "multipart/form-data"}))
    {
        <div class="row">

            <div class="col">
                <div class="form-group">
                    @Html.LabelFor(x => x.Title)
                    @Html.TextBoxFor(x => x.Title, new {@class = "form-control"})
                </div>
                <div class="form-group">
                    @Html.LabelFor(x => x.Description)
                    @Html.TextAreaFor(x => x.Description, new {@class = "form-control"})
                </div>
                <div>
                    <button type="submit" class="p-2 btn-primary mb-2">Send Kommentar</button>
                </div>
            </div>
        </div>

    }
</div>